---
title: "visualize aqs"
author: "Colby Wilkinson"
date: "11/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

Reading in data

```{r}
aqs_data <- data.table::fread("../../data/final/AQS HOURLY.csv")
```

Plot of pm 2.5 over the base 10 years, by City

```{r, dpi=150, fig.height=10, fig.width=7.5}
aqs_data %>% 
  mutate(date = ymd_hm(paste(date, hour, sep = " "))) %>% 
  filter(date > date('2010-01-01')) %>% 
  filter(city != "Houston") %>% 
  ggplot(aes(x = date, y = pm25_local)) +
  geom_point(color = 'darkcyan', alpha = 0.6) +
  geom_smooth(color = 'firebrick2') +
  facet_wrap(~city, nrow = 5) +
  theme(axis.text = element_text(size = 7)) +
  theme(strip.text = element_text(size = 8)) +
  theme(axis.title = element_text(size = 7)) +
  ylab("PM 2.5 (Micrograms/cubic meter)") +
  xlab("") +
  theme(axis.text.x=element_text(angle=60, hjust=1)) +
  ggsave("../../plots/pm25_by_city.jpeg")

```

Ozone levels in previous 10 years

```{r}
aqs_data %>% 
  mutate(date = ymd_hm(paste(date, hour, sep = " "))) %>% 
  filter(date > date('2010-01-01')) %>% 
  filter(city != "Houston") %>% 
  mutate(year = year(date)) %>% 
  group_by(year, city) %>% 
  summarise(ozone = mean(ozone, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = ozone, col = city)) +
  geom_line() +
  geom_point() +
  xlab("Year") +
  ylab("Average Ozone (ppm)") +
  ggtitle("Average Annual Ozone (ppm) by City") +
  theme(plot.title = element_text(hjust = 0.5, size = 14)) + 
  scale_colour_discrete(name = "") +
  scale_x_continuous(breaks = 2010:2019)
```

Carbon Monoxide levels in previous 5 years

```{r}
aqs_data %>% 
  mutate(date = ymd_hm(paste(date, hour, sep = " "))) %>% 
  filter(date > date('2014-01-01')) %>% 
  filter(city != "Chicago") %>% 
  mutate(year = year(date)) %>% 
  group_by(year, city) %>% 
  summarise(ozone = mean(CO, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = ozone, col = city)) +
  geom_line() +
  geom_point() +
  xlab("Year") +
  ylab("Average CO (ppm)") +
  ggtitle("Average Annual Carbon Monoxide Level (ppm) by City") +
  theme(plot.title = element_text(hjust = 0.5, size = 14)) + 
  scale_colour_discrete(name = "") +
  scale_x_continuous(breaks = 2010:2019)
```
